apiVersion: v1
kind: Service
metadata:
  name: biostudio-service
spec:
  selector:
    app: biostudio
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort  # or LoadBalancer if using cloud
