apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJtYW40aXNoIiwicGFzc3dvcmQiOiIwSGFudW1hbjAwNyIsImVtYWlsIjoibWFuZGVjZW50Lmd1cHRhQGdtYWlsLmNvbSIsImF1dGgiOiJiV0Z1TkdsemFEb3dTR0Z1ZFcxaGJqQXdOdz09In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
