# Generated by Django 4.2 on 2025-06-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bioagent", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotatedfile",
            name="email",
        ),
        migrations.AlterField(
            model_name="annotatedfile",
            name="file",
            field=models.FileField(upload_to="bioagent/"),
        ),
    ]
